apiVersion: v1
kind: Service
metadata:
  name: simplestapp
  labels:
    tier: backend
    lab: simple
spec:
  type: NodePort
  ports:
  - name: application
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    lab: simple
    tier: backend