apiVersion: v1
kind: Service
metadata:
  name: simplestdb
  labels:
    tier: database
    lab: simple
spec:
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    lab: simple
    tier: database