apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplestapp
  labels:
    tier: backend
    lab: simple
spec:
  selector:
    matchLabels:
      tier: backend
      lab: simple
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: backend
        lab: simple
    spec:
      containers:
      - image: codegazers/simplest-lab:simplestapp
        name: simplestapp
        env:
        - name: dbhost
          value: simplestdb
        - name: dbname
          value: "demo"
        - name: dbuser
          value: "demo"
        - name: dbpasswd
          value: "d3m0"                    
        ports:
        - containerPort: 3000
          name: simplestapp
